/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HireRouteImport } from './routes/hire'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ShortlistRouteImport } from './routes/shortlist'
import { Route as RegionsSlugRouteImport } from './routes/regions/$slug'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as RolesSlugRouteImport } from './routes/roles/$slug'
import { Route as TalentIndexRouteImport } from './routes/talent/index'
import { Route as TalentIdRouteImport } from './routes/talent/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistRoute = ShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsSlugRoute = RegionsSlugRouteImport.update({
  id: '/regions/$slug',
  path: '/regions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesSlugRoute = RolesSlugRouteImport.update({
  id: '/roles/$slug',
  path: '/roles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/talent/',
  path: '/talent/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIdRoute = TalentIdRouteImport.update({
  id: '/talent/$id',
  path: '/talent/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hire': typeof HireRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/shortlist': typeof ShortlistRoute
  '/regions/$slug': typeof RegionsSlugRoute
  '/roles/$slug': typeof RolesSlugRoute
  '/talent/$id': typeof TalentIdRoute
  '/roles/': typeof RolesIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hire': typeof HireRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/shortlist': typeof ShortlistRoute
  '/regions/$slug': typeof RegionsSlugRoute
  '/roles/$slug': typeof RolesSlugRoute
  '/talent/$id': typeof TalentIdRoute
  '/roles': typeof RolesIndexRoute
  '/talent': typeof TalentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hire': typeof HireRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/shortlist': typeof ShortlistRoute
  '/regions/$slug': typeof RegionsSlugRoute
  '/roles/$slug': typeof RolesSlugRoute
  '/talent/$id': typeof TalentIdRoute
  '/roles/': typeof RolesIndexRoute
  '/talent/': typeof TalentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/hire'
    | '/how-it-works'
    | '/pricing'
    | '/shortlist'
    | '/regions/$slug'
    | '/roles/$slug'
    | '/talent/$id'
    | '/roles/'
    | '/talent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/hire'
    | '/how-it-works'
    | '/pricing'
    | '/shortlist'
    | '/regions/$slug'
    | '/roles/$slug'
    | '/talent/$id'
    | '/roles'
    | '/talent'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/hire'
    | '/how-it-works'
    | '/pricing'
    | '/shortlist'
    | '/regions/$slug'
    | '/roles/$slug'
    | '/talent/$id'
    | '/roles/'
    | '/talent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HireRoute: typeof HireRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  ShortlistRoute: typeof ShortlistRoute
  RegionsSlugRoute: typeof RegionsSlugRoute
  RolesSlugRoute: typeof RolesSlugRoute
  TalentIdRoute: typeof TalentIdRoute
  RolesIndexRoute: typeof RolesIndexRoute
  TalentIndexRoute: typeof TalentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlist': {
      id: '/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof ShortlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions/$slug': {
      id: '/regions/$slug'
      path: '/regions/$slug'
      fullPath: '/regions/$slug'
      preLoaderRoute: typeof RegionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$slug': {
      id: '/roles/$slug'
      path: '/roles/$slug'
      fullPath: '/roles/$slug'
      preLoaderRoute: typeof RolesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/': {
      id: '/talent/'
      path: '/talent'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/$id': {
      id: '/talent/$id'
      path: '/talent/$id'
      fullPath: '/talent/$id'
      preLoaderRoute: typeof TalentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HireRoute: HireRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  ShortlistRoute: ShortlistRoute,
  RegionsSlugRoute: RegionsSlugRoute,
  RolesSlugRoute: RolesSlugRoute,
  TalentIdRoute: TalentIdRoute,
  RolesIndexRoute: RolesIndexRoute,
  TalentIndexRoute: TalentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
